{% set name = "pytest-cram" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00e358dff2836239cab47d846656d3029035a5ebb60c0cb188d16c9d6bf50510

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytest >=2.8
    - cram >=0.7

test:
  imports:
    - cram
    - pytest_cram

about:
  home: https://pypi.org/project/pytest-cram
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Run cram tests with pytest
  description: |
    cram tests command line applications. pytest tests Python applications.
    pytest-cram tests Python command line applications by letting you write
    your Python API tests with pytest, and your command line tests in cram.
    Best of both worlds!
  doc_url: https://pypi.org/project/pytest-cram
  dev_url: https://github.com/tbekolay/pytest-cram

extra:
  recipe-maintainers:
    - kynan
